Repository mono/SkiaSharp, pull requests merged in 2018-12, with the labels that each got.

#716 Added mouse wheel handling for Forms.UWP
  source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Shared/SKTouchEventArgs.cs
  source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.UWP/SKTouchHandler.cs
Labels: area-SkiaSharp.Views.Forms, azdo-sync, enhancement

#737 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: area-Docs

#740 Updated the projects
  VERSIONS.txt
  binding/HarfBuzzSharp.Android/HarfBuzzSharp.Android.csproj
  binding/HarfBuzzSharp.Desktop/HarfBuzzSharp.Desktop.csproj
  binding/HarfBuzzSharp.NetStandard/HarfBuzzSharp.NetStandard.csproj
  binding/HarfBuzzSharp.OSX/HarfBuzzSharp.OSX.csproj
  binding/HarfBuzzSharp.Tizen/HarfBuzzSharp.Tizen.csproj
  binding/HarfBuzzSharp.UWP/HarfBuzzSharp.UWP.csproj
  binding/HarfBuzzSharp.iOS/HarfBuzzSharp.iOS.csproj
  binding/HarfBuzzSharp.tvOS/HarfBuzzSharp.tvOS.csproj
  binding/HarfBuzzSharp.watchOS/HarfBuzzSharp.watchOS.csproj
  binding/SkiaSharp.Android/SkiaSharp.Android.csproj
  binding/SkiaSharp.Desktop/SkiaSharp.Desktop.csproj
  binding/SkiaSharp.NetStandard/SkiaSharp.NetStandard.csproj
  binding/SkiaSharp.OSX/SkiaSharp.OSX.csproj
  binding/SkiaSharp.Tizen/SkiaSharp.Tizen.csproj
  binding/SkiaSharp.UWP/SkiaSharp.UWP.csproj
  binding/SkiaSharp.iOS/SkiaSharp.iOS.csproj
  binding/SkiaSharp.tvOS/SkiaSharp.tvOS.csproj
  binding/SkiaSharp.watchOS/SkiaSharp.watchOS.csproj
  global.json
  samples/Basic/ElmSharp/SkiaSharpSample/SkiaSharpSample.csproj
  samples/Basic/Tizen/SkiaSharpSample/SkiaSharpSample.csproj
  samples/Basic/Xamarin.Forms/SkiaSharpSample.Tizen/SkiaSharpSample.Tizen.csproj
  samples/Gallery/Xamarin.Forms/Tizen/TizenOS.csproj
  source/SkiaSharp.HarfBuzz/SkiaSharp.HarfBuzz.Desktop/SkiaSharp.HarfBuzz.Desktop.csproj
  source/SkiaSharp.HarfBuzz/SkiaSharp.HarfBuzz/SkiaSharp.HarfBuzz.csproj
  source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Android/SkiaSharp.Views.Forms.Android.csproj
  source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Mac/SkiaSharp.Views.Forms.Mac.csproj
  source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Tizen/SkiaSharp.Views.Forms.Tizen.csproj
  source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.UWP/SkiaSharp.Views.Forms.UWP.csproj
  source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.iOS/SkiaSharp.Views.Forms.iOS.csproj
  source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.csproj
  source/SkiaSharp.Views/SkiaSharp.Views.Android/SKGLSurfaceViewRenderer.cs
  source/SkiaSharp.Views/SkiaSharp.Views.Android/SKGLTextureViewRenderer.cs
  source/SkiaSharp.Views/SkiaSharp.Views.Android/SkiaSharp.Views.Android.csproj
  source/SkiaSharp.Views/SkiaSharp.Views.Desktop/SkiaSharp.Views.Desktop.csproj
  source/SkiaSharp.Views/SkiaSharp.Views.Gtk/SkiaSharp.Views.Gtk.csproj
  source/SkiaSharp.Views/SkiaSharp.Views.Mac/SkiaSharp.Views.Mac.csproj
  source/SkiaSharp.Views/SkiaSharp.Views.Tizen/SkiaSharp.Views.Tizen.csproj
  source/SkiaSharp.Views/SkiaSharp.Views.UWP/SkiaSharp.Views.UWP.csproj
  source/SkiaSharp.Views/SkiaSharp.Views.WPF/SkiaSharp.Views.WPF.csproj
  source/SkiaSharp.Views/SkiaSharp.Views.iOS/SkiaSharp.Views.iOS.csproj
  source/SkiaSharp.Views/SkiaSharp.Views.tvOS/SkiaSharp.Views.tvOS.csproj
  source/SkiaSharp.Views/SkiaSharp.Views.watchOS/SkiaSharp.Views.watchOS.csproj
  source/SkiaSharp.Workbooks/SkiaSharp.Workbooks.csproj
Labels: area-Build, enhancement
