Repository mono/SkiaSharp, pull requests merged in 2019-12, with the labels that each got.

#1039 TryRemove SKObject.instances WeakReferences
  binding/Binding/SKObject.cs
Labels: type-bug

#1055 Correctly decode images
  binding/Binding/SKImage.cs
  tests/Content/images/vimeo_icon_dark.png
  tests/Tests/SKImageTest.cs
Labels: type-bug

#1057 Add the .targets file to buildTransitive
  nuget/HarfbuzzSharp.NativeAssets.Linux.nuspec
  nuget/HarfbuzzSharp.nuspec
  nuget/SkiaSharp.NativeAssets.Linux.NoDependencies.nuspec
  nuget/SkiaSharp.NativeAssets.Linux.nuspec
  nuget/SkiaSharp.NativeAssets.NanoServer.nuspec
  nuget/SkiaSharp.nuspec
Labels: area-Build, area-HarfBuzzSharp, area-SkiaSharp, type-enhancement

#1060 Don't go straight for the max samples
  source/SkiaSharp.Views/SkiaSharp.Views.WindowsForms/SKGLControl.cs
Labels: area-SkiaSharp.Views, backend-OpenGL, os-Windows-Classic, type-bug

#1077 Update to v1.68.2
  VERSIONS.txt
  scripts/azure-pipelines.yml
Labels: area-Build
