Repository mono/SkiaSharp, pull requests merged in 2022-05, with the labels that each got.

#2054 Return null on invalid resize bounds
  binding/Binding/SKBitmap.cs
  tests/Tests/SKBitmapTest.cs
Labels: type/bug, area/SkiaSharp

#2083 Use macOS 11 to get things green
  scripts/azure-pipelines-complete.yml
  scripts/azure-templates-stages.yml
Labels: area/Build

#2086 fix(unowasm): Adds missing Uno.WinUI javascript support file
  source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Wasm/SKSwapChainPanel.Wasm.cs
  source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.Wasm/SKXamlCanvas.Wasm.cs
  source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.WinUI.Wasm/SkiaSharp.Views.Uno.WinUI.Wasm.csproj
  source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.WinUI.Wasm/WasmScripts/SkiaSharp.Views.Uno.Wasm.js
Labels: type/bug, area/SkiaSharp.Views.Uno, partner/unoplatform

#2087 Update Generator & Added Nested Namespace Support
  binding/Binding/SkiaApi.generated.cs
  binding/HarfBuzzSharp.Shared/HarfBuzzApi.generated.cs
  binding/libHarfBuzzSharp.json
  binding/libSkiaSharp.json
  utils/SkiaSharpGenerator/BaseTool.cs
  utils/SkiaSharpGenerator/ConfigJson/Config.cs
  utils/SkiaSharpGenerator/ConfigJson/NamespaceMapping.cs
  utils/SkiaSharpGenerator/Generate/Generator.cs
  utils/SkiaSharpGenerator/Generate/Utils.cs
  utils/SkiaSharpGenerator/SkiaSharpGenerator.csproj
Labels: area/Build
